### ISSUE TITLE
Error told me to create an issue

### ISSUE THREAD

**Issue by adamhinckley** [typed-rocks/ts-worksheet#1] opened 2024-02-12 20:04 UTC
I work with a few repos at work that us TS.  When I add `//ts-worksheet` at the top of any file and save I get this error:
```
ts-worksheet: An Error happend during the running of the worksheet. If you think there is something wrong with the plugin, please file an issue: : Error: Manipulation error: A syntax error was inserted. [96mUsers/adam.hinckley/projects/exit-offer-customizer-ui/src/util/.toedit.ts[0m:[93m123[0m:[93m13[0m - [91merror[0m[90m TS1005: [0m'>' expected. [7m123[0m status="error" [7m [0m [91m ~~~~~~[0m [96mUsers/adam.hinckley/projects/exit-offer-customizer-ui/src/util/.toedit.ts[0m:[93m123[0m:[93m19[0m - [91merror[0m[90m TS1005: [0m',' expected. [7m123[0m status="error" [7m [0m [91m ~[0m [96mUsers/adam.hinckley/projects/exit-offer-customizer-ui/src/util/.toedit.ts[0m:[93m124[0m:[93m13[0m - [91merror[0m[90m TS1005: [0m',' expected. [7m124[0m message={ [7m [0m [91m ~~~~~~~[0m [96mUsers/adam.hinckley/projects/exit-offer-customizer-ui/src/util/.toedit.ts[0m:[93...
```
It looks like it's saying there is a file called `.toedit.ts` in my util folder, but that file does not exist in my repo anywhere.

**Comment by chwoerz** [comment] 2024-02-12 20:22
Hi thanks for opening this issue. Could you show me the file you added //ts-worksheet to it? This .toedit.ts is a temporary file which gets created by ts-morph.

**Comment by chwoerz** [comment] 2024-02-12 20:23
It looks like wrapping code which i create from your file is not valid

**Comment by smol-honk** [comment] 2024-02-13 15:18
I'm getting the same thing. It seems to break on my [stitches](https://stitches.dev/) components.

**Comment by chwoerz** [comment] 2024-02-13 17:13
@smol-honk do you have a code example?

**Comment by smol-honk** [comment] 2024-02-13 17:48
> @smol-honk do you have a code example?

Unfortunately it's my work code. I'll try to put together something with the same stack to share.

**Comment by chwoerz** [comment] 2024-02-13 17:54
Would be great. A minimal reproducible example would be nice.

**Comment by chwoerz** [comment] 2024-02-13 22:06
I've done a basic example with styled and createStitches but did not receive any errors. Would be great to see where it fails for you. Which function for example.

**Comment by chwoerz** [comment] 2024-12-27 15:13
Currently it's not possible to support stuff beside ts files. So I sadly have to close the issue

**Closed** 2024-12-27 15:14 UTC
